export const RESET_FAVORIT_MERCHANTS = 'RESET_FAVORIT_MERCHANTS';
export const GET_FAVORIT_MERCHANTS = 'GET_FAVORIT_MERCHANTS';
export const SET_FAVORIT_MERCHANTS = 'SET_FAVORIT_MERCHANTS';
export const DELETE_FROM_FAVORIT = 'DELETE_FROM_FAVORIT';
export const ADD_TO_FAVORIT = 'ADD_TO_FAVORIT';
